CREATE TABLE config_revisions (
    id VARCHAR(36) NOT NULL,
    item_id VARCHAR(36) NOT NULL,
    namespace_id VARCHAR(36) NOT NULL,
    revision_number INT UNSIGNED NOT NULL,
    value_type ENUM('string', 'integer', 'decimal', 'boolean', 'json', 'single_asset', 'multi_asset', 'single_relation', 'multi_relation') NOT NULL,
    constraints JSON NOT NULL,
    `value` JSON NOT NULL,
    workflow_status ENUM('draft', 'pending_review', 'rejected', 'published', 'unpublished') NOT NULL DEFAULT 'draft',
    created_by VARCHAR(64) NOT NULL,
    submitted_by VARCHAR(64) NULL,
    submitted_at DATETIME(6) NULL,
    created_at DATETIME(6) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_config_revisions_item_number (item_id, revision_number),
    UNIQUE KEY uq_config_revisions_id_item_namespace (id, item_id, namespace_id),
    KEY idx_config_revisions_item_page (item_id, revision_number DESC),
    KEY idx_config_revisions_workflow (namespace_id, item_id, workflow_status, revision_number DESC),
    CONSTRAINT fk_config_revisions_item FOREIGN KEY (item_id, namespace_id) REFERENCES config_items (id, namespace_id),
    CONSTRAINT fk_config_revisions_creator FOREIGN KEY (created_by) REFERENCES users (id),
    CONSTRAINT fk_config_revisions_submitter FOREIGN KEY (submitted_by) REFERENCES users (id),
    CONSTRAINT chk_config_revisions_number CHECK (revision_number >= 1),
    CONSTRAINT chk_config_revisions_submission CHECK ((workflow_status = 'draft' AND submitted_by IS NULL AND submitted_at IS NULL) OR (workflow_status <> 'draft' AND submitted_by IS NOT NULL AND submitted_at IS NOT NULL))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_as_cs;
