CREATE TABLE content_fields (
    id VARCHAR(36) NOT NULL,
    model_id VARCHAR(36) NOT NULL,
    parent_id VARCHAR(36) NULL,
    field_key VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    display_name VARCHAR(120) NOT NULL,
    description VARCHAR(1000) NOT NULL DEFAULT '',
    field_type ENUM('single_line_text','multi_line_text','rich_text','integer','decimal','boolean','date','datetime','single_select','multi_select','json','single_media','multi_media','single_relation','multi_relation','object','repeatable_group') NOT NULL,
    is_required BOOLEAN NOT NULL DEFAULT FALSE,
    default_value JSON NOT NULL,
    constraints JSON NOT NULL,
    status ENUM('active', 'archived') NOT NULL DEFAULT 'active',
    depth TINYINT UNSIGNED NOT NULL,
    position INT UNSIGNED NOT NULL,
    created_at DATETIME(6) NOT NULL,
    updated_at DATETIME(6) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_content_fields_id_model (id, model_id),
    UNIQUE KEY uq_content_fields_model_key (model_id, field_key),
    KEY idx_content_fields_model_tree (model_id, depth, parent_id, position),
    CONSTRAINT fk_content_fields_model FOREIGN KEY (model_id) REFERENCES content_models (id),
    CONSTRAINT fk_content_fields_parent FOREIGN KEY (parent_id, model_id) REFERENCES content_fields (id, model_id),
    CONSTRAINT chk_content_fields_key CHECK (field_key REGEXP _ascii'^[a-z][a-z0-9_]{0,63}$'),
    CONSTRAINT chk_content_fields_depth CHECK (depth <= 2),
    CONSTRAINT chk_content_fields_parent_depth CHECK ((depth = 0 AND parent_id IS NULL) OR (depth > 0 AND parent_id IS NOT NULL))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_as_cs;
